"""add user and recipe models

Revision ID: fdc7ce4fcc0d
Revises: 5db054d28af3
Create Date: 2025-03-25 18:12:52.532128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc7ce4fcc0d'
down_revision = '5db054d28af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
